<a href="https://colab.research.google.com/github/TilakSojitra/Machine-Learning/blob/master/ML6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# /content/drive/MyDrive/Colab Notebooks/tweets.csv

In [ ]:
# importing some required libraries
import pandas as pd
import re
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import classification_report
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import seaborn as sns
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# reading the dataset
columns = ["sentiment", "id", "date", "query", "user_id", "text"]
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/tweets.csv", encoding="latin",names=columns)
df.head()

# replacing the '4' with '1' as positive sentiment
df["sentiment"] = df["sentiment"].replace(4,1)

# plotting the data using countplot
sns.countplot(x="sentiment",data=df)

# creating a string of positive tweets to analyze the words
positive_tweets = df[df['sentiment'] == 1]['text'].tolist()
positive_tweets_string = " ".join(positive_tweets)
plt.figure(figsize=(15,15))
plt.imshow(WordCloud().generate(positive_tweets_string))

# creating the string of negative tweets to analyze the words
negative_tweets = df[df['sentiment'] == 0]['text'].tolist()
negative_tweets_string = " ".join(negative_tweets)
plt.figure(figsize=(15,15))
plt.imshow(WordCloud().generate(negative_tweets_string))

#removing stopwords,urls from the dataset
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import TweetTokenizer
import string

import re
# remove hyperlinks
positive_tweets_string = re.sub(r'https?:\/\/.*[\r\n]*', '', positive_tweets_string)
# remove hashtags
# only removing the hash # sign from the word
positive_tweets_string = re.sub(r'#', '', positive_tweets_string)
print(positive_tweets_string)

#Import the english stop words list from NLTK
stopwords_english = stopwords.words('english')
# print('Stop words\n')
# print(stopwords_english)
positive_tweets_clean=[]

#Tokenize the string
# instantiate tokenizer class
tokenizer = TweetTokenizer(preserve_case=False)

# tokenize tweets
positive_tweet_tokens = tokenizer.tokenize(positive_tweets_string)

print()
print('Tokenized string:')
print(positive_tweet_tokens[:30])
for word in positive_tweet_tokens:
    if (word not in stopwords_english and word not in string.punctuation) :
      positive_tweets_clean.append(word)
print('Removed stopwords')
print(positive_tweets_clean[:30])

#Selecting the text and Sentiment column for our further analysis
data=df[['text','sentiment']]

#: Separating positive and negative tweets
data_pos = data[data['sentiment'] == 1]
data_neg = data[data['sentiment'] == 0]

#Combining positive and negative tweets
dataset = pd.concat([data_pos, data_neg])

#Making statement text in lower case
dataset['text']=dataset['text'].str.lower()
dataset

#Cleaning and removing the above stop words list from the tweet text
stopwordlist = stopwords.words('english')
STOPWORDS = set(stopwordlist)
def cleaning_stopwords(text):
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])
dataset['text'] = dataset['text'].apply(lambda text: cleaning_stopwords(text))

def cleaning_punctuations(text):
    translator = str.maketrans('', '', string.punctuation)#removes punctuation
    return text.translate(translator)

dataset['text']= dataset['text'].apply(lambda x: cleaning_punctuations(x))

dataset['text'] = dataset['text'].apply(lambda x: re.sub('((www.[^s]+)|(https?://[^s]+))',' ',x))

dataset

#Getting tokenization of tweet text
from nltk.tokenize import TweetTokenizer
tokenizer = TweetTokenizer(preserve_case=False)
dataset['text'] = dataset['text'].apply(tokenizer.tokenize)
dataset['text'].head()

#Applying Stemming
import nltk
st = nltk.PorterStemmer()
def stemming_on_text(data):
    text = [st.stem(word) for word in data ]
    return data
dataset['text']= dataset['text'].apply(lambda x:stemming_on_text(x))
dataset['text'].head()

import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

#Applying Lemmatizer
from nltk.stem import WordNetLemmatizer
lm = nltk.WordNetLemmatizer()
def lemmatizer_on_text(data):
  text = [lm.lemmatize(word) for word in data]
  return data
dataset['text'] = dataset['text'].apply(lambda x:lemmatizer_on_text(x))
dataset['text'].head()

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/tweets.csv", encoding="latin",names=columns)
df.head()

,sentiment,id,date,query,user_id,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."